<?xml version="1.0" ?>
<testsuite name="unittest.loader._FailedTest-20240620165800" tests="1" time="0.000" failures="0" errors="1">
	<testcase classname="unittest.loader._FailedTest" name="test_keplerSTM" time="0.000">
		<error type="ImportError" message="Failed to import test module: test_keplerSTM
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/Users/maxzweig/research/EXOSIMS/tests/util/test_keplerSTM.py&quot;, line 17, in &lt;module&gt;
    import keplertools.keplerSTM as keplerSTM
ModuleNotFoundError: No module named 'keplertools'
"><![CDATA[ImportError: Failed to import test module: test_keplerSTM
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/maxzweig/research/EXOSIMS/tests/util/test_keplerSTM.py", line 17, in <module>
    import keplertools.keplerSTM as keplerSTM
ModuleNotFoundError: No module named 'keplertools'

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
